apiVersion: v1
kind: Service
metadata:
  name: docker-registry-nodeport
  namespace: registry
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
      protocol: TCP
      name: docker-registry
  selector:
    app: docker-registry