apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apigw-healthcheck-ingress
  namespace: ekyc-vnpt
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"          # allow large uploads
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/rewrite-target: /actuator/health
spec:
  rules:
  - http:
      paths:
      - path: /vnpt-ekyc/live/health
        pathType: Prefix
        backend:
          service:
            name: apigateway-service
            port:
              number: 8762
